"""filmsdb

Revision ID: 8e522ca2579f
Revises: 09aae46f4797
Create Date: 2020-11-22 13:45:07.209275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e522ca2579f'
down_revision = '09aae46f4797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('watched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'watched')
    # ### end Alembic commands ###
